apiVersion: v1
kind: Pod
metadata:
  name: janni-webseite
  labels:
    app: website
spec:
  containers:
  - name: webserver
    image: localhost/janni-webseite:v1
    imagePullPolicy: Never
    ports:
    - containerPort: 80